/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.daf.view;

import org.daf.consulta.ControllerDependente;
import org.daf.consulta.ControllerPessoa;
import org.daf.entidade.Dependente;
import org.daf.entidade.Pessoa;

/**
 *
 * @author leandro
 */
public class FormDependentes extends javax.swing.JDialog {

    /**
     * Creates new form FormDependentes
     */
    public FormDependentes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtContato = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Email:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 110, 70, 30);

        jLabel2.setText("Contato:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 170, 80, 17);

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 60, 45, 30);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(100, 110, 330, 27);
        getContentPane().add(txtNome);
        txtNome.setBounds(100, 60, 330, 27);
        getContentPane().add(txtContato);
        txtContato.setBounds(100, 160, 330, 27);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(100, 210, 60, 29);

        jButton2.setText("Limpar");
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 210, 66, 29);

        jButton3.setText("Cancelar");
        getContentPane().add(jButton3);
        jButton3.setBounds(290, 210, 84, 29);

        jLabel4.setText("Cadastrar Dependente:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 20, 290, 17);

        setSize(new java.awt.Dimension(473, 341));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        ControllerDependente cp = ControllerDependente.instanceOF();
        Dependente d = new Dependente();
        d.setNome(txtNome.getText());
        d.setEmail(txtEmail.getText());
        d.setContato(txtContato.getText());
        d.setPessoa(pessoa);
        cp.save(d);

        TelaPessoaConsultar.atualizarTableView(pessoa.getIdPessoa());
        pessoa = null;
    }//GEN-LAST:event_jButton1ActionPerformed
    private static Pessoa pessoa = null;

    public static void carregarForm(Pessoa p) {
        pessoa = p;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(FormDependentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormDependentes dialog = new FormDependentes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField txtContato;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
